
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("ForecastParameter")]
    public partial class ForecastParameter
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastParameter()
        {
             this.ForecastParameterDetails_ForecastParemeter = new HashSet<ForecastParameterDetail>();  //FK_ForecastParameterDetails_ForecastParameter
        AfterConstructor();
        }
    
        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();
    
            /// <summary></summary>
            [Key]
            
            
            public int ForecastParameterId { get; set; }
            /// <summary></summary>
            
            
            
            public int? CaseId { get; set; }
            /// <summary></summary>
            
            
            
            public int WellId { get; set; }
            /// <summary></summary>
            
            
            
            public int AssetTeamId { get; set; }
            /// <summary></summary>
            
            
            
            public bool IsActive { get; set; }
            /// <summary></summary>
            
            
            
            public DateTime EffectiveDate { get; set; }
            /// <summary></summary>
            
            
            
            public DateTime WalkDate { get; set; }
            /// <summary></summary>
            
            
            
            public int? ForecastHorizontalId { get; set; }
        /// <summary>FK_ForecastParameterDetails_ForecastParameter</summary> 
         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")] 
         public virtual ICollection<ForecastParameterDetail> ForecastParameterDetails_ForecastParemeter { get; set; }
            
        /// <summary>FK_ForecastParameter_ForecastHorizontal</summary>
        [ForeignKey("ForecastHorizontalId")]
        public virtual ForecastHorizontal ForecastHorizontal { get; set; }
        /// <summary>FK_ForecastWellHeader_Wells</summary>
        [ForeignKey("WellId")]
        public virtual Well Well { get; set; }

    }
}
