
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("ForecastWellRisks")]
    public partial class ForecastWellRisk
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastWellRisk()
        {
        AfterConstructor();
        }
    
        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();
    
            /// <summary></summary>
            [Key]
            [ForeignKey("ForecastHorizontal")]
            
            public int ForecastWellRiskId { get; set; }
            /// <summary></summary>
            
            
            
            public int ScenarioWellId { get; set; }
            /// <summary></summary>
            
            
            
            public double Oil { get; set; }
            /// <summary></summary>
            
            
            
            public double Gas { get; set; }
            /// <summary></summary>
            
            
            
            public double Water { get; set; }
        /// <summary>FK_ForecastWellRisks_ForecastHorizontal</summary>
        public virtual ForecastHorizontal ForecastHorizontal { get; set; }

    }
}
