
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("ForecastVerticals")]
    public partial class ForecastVertical
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastVertical()
        {
             this.ForecastVerticalDetails_ForecastVertical = new HashSet<ForecastVerticalDetail>();  //FK_ForecastVerticalDetails_ForecastVerticals
        AfterConstructor();
        }
    
        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();
    
            /// <summary></summary>
            [Key]
            
            
            public int ForecastVerticalId { get; set; }
            /// <summary></summary>
            
            
            
            public int BusinessUnitId { get; set; }
            /// <summary></summary>
            
            
            
            public string Name { get; set; }
            /// <summary></summary>
            
            
            
            public string Description { get; set; }
            /// <summary></summary>
            
            
            
            public string IsApproved { get; set; }
            /// <summary></summary>
            
            
            
            public int? ForecastId { get; set; }
        /// <summary>FK_ForecastVerticalDetails_ForecastVerticals</summary> 
         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")] 
         public virtual ICollection<ForecastVerticalDetail> ForecastVerticalDetails_ForecastVertical { get; set; }
            
        /// <summary>FK_ForecastVerticals_Forecasts</summary>
        [ForeignKey("ForecastId")]
        public virtual Forecast Forecast { get; set; }

    }
}
