
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("Forecasts")]
    public partial class Forecast
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forecast()
        {
             this.ForecastHorizontal_Forecast = new HashSet<ForecastHorizontal>();  //FK_ForecastHorizontal_Forecast
             this.ForecastVerticals_Forecast = new HashSet<ForecastVertical>();  //FK_ForecastVerticals_Forecasts
        AfterConstructor();
        }
    
        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();
    
            /// <summary></summary>
            [Key]
            
            
            public int ForecastId { get; set; }
            /// <summary></summary>
            
            
            
            public int ScenarioId { get; set; }
            /// <summary></summary>
            
            
            
            public string Name { get; set; }
            /// <summary></summary>
            
            
            
            public string Description { get; set; }
        /// <summary>FK_ForecastHorizontal_Forecast</summary> 
         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")] 
         public virtual ICollection<ForecastHorizontal> ForecastHorizontal_Forecast { get; set; }
            
        /// <summary>FK_ForecastVerticals_Forecasts</summary> 
         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")] 
         public virtual ICollection<ForecastVertical> ForecastVerticals_Forecast { get; set; }
            
        /// <summary>FK_Forecast_Scenarios</summary>
        //[ForeignKey("ScenarioId")]
        //public virtual Scenario Scenario { get; set; }

    }
}
