
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("ForecastSeasonalRisks")]
    public partial class ForecastSeasonalRisk
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastSeasonalRisk()
        {
        AfterConstructor();
        }
    
        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();
    
            /// <summary></summary>
            [Key]
            
            
            public int ForecastSeasonalRiskId { get; set; }
            /// <summary></summary>
            
            
            
            public int ForecastHorizontalId { get; set; }
            /// <summary></summary>
            
            
            
            public double? Oil { get; set; }
            /// <summary></summary>
            
            
            
            public double? Water { get; set; }
            /// <summary></summary>
            
            
            
            public double? Gas { get; set; }
            /// <summary></summary>
            
            
            
            public int? Month { get; set; }
        /// <summary>FK_ForecastSeasonalRisks_ForecastHorizontal</summary>
        [ForeignKey("ForecastHorizontalId")]
        public virtual ForecastHorizontal ForecastHorizontal { get; set; }

    }
}
