
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("ForecastParemeterProductTypes")]
    public partial class ForecastParemeterProductType
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastParemeterProductType()
        {
             this.ForecastParameterDetails_ForecastParamterProductType = new HashSet<ForecastParameterDetail>();  //FK_ForecastParameters_ForecastProductTypes
             //this.TypeCurveParameters_ForecastProductType = new HashSet<TypeCurveParameter>();  //FK_TypecurveParameters_ForecastProductTypes
        AfterConstructor();
        }
    
        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();
    
            /// <summary></summary>
            [Key]
            
            
            public int ForecastParameterProductTypeId { get; set; }
            /// <summary></summary>
            
            
            
            public string Name { get; set; }
        /// <summary>FK_ForecastParameters_ForecastProductTypes</summary> 
         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")] 
         public virtual ICollection<ForecastParameterDetail> ForecastParameterDetails_ForecastParamterProductType { get; set; }
            
        /// <summary>FK_TypecurveParameters_ForecastProductTypes</summary> 
         //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")] 
         //public virtual ICollection<TypeCurveParameter> TypeCurveParameters_ForecastProductType { get; set; }
            

    }
}
