
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("ForecastHorizontalBase")]
    public partial class ForecastHorizontalBase
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastHorizontalBase()
        {
             this.ForecastHorizontalBaseDetails_ForecastHorizontalBase = new HashSet<ForecastHorizontalBaseDetail>();  //FK_ForecastHorizontalBaseDetails_ForecastHorizontalBase
        AfterConstructor();
        }
    
        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();
    
            /// <summary></summary>
            [Key]
            
            
            public int ForecastHorizontalBaseId { get; set; }
            /// <summary></summary>
            
            
            
            public int WellId { get; set; }
            /// <summary></summary>
            
            
            
            public string Name { get; set; }
            /// <summary></summary>
            
            
            
            public string Description { get; set; }
        /// <summary>FK_ForecastHorizontalBaseDetails_ForecastHorizontalBase</summary> 
         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")] 
         public virtual ICollection<ForecastHorizontalBaseDetail> ForecastHorizontalBaseDetails_ForecastHorizontalBase { get; set; }
            

    }
}
