
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CppeDb.DataAccess.Models
{
    /// <summary></summary>
    [Table("ForecastDeclineCurveTypes")]
    public partial class ForecastDeclineCurveType
    {

        /// <summary></summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastDeclineCurveType()
        {
            this.ForecastParameterDetails_ForecastDeclineCurveType = new HashSet<ForecastParameterDetail>();  //FK_ForecastParameters_ForecastDeclineCurveTypes
                                                                                                              //this.TypeCurveParameters_ForecastDeclineCurveType = new HashSet<TypeCurveParameter>();  //FK_TypecurveParameters_ForecastDeclineCurveTypes
            AfterConstructor();
        }

        ///<summary>Provide the actual method AfterConstructor() in a partial class and it will get called as the last point in construction.</summary>
        partial void AfterConstructor();

        /// <summary></summary>
        [Key]


        public int ForecastDeclineCurveTypeId { get; set; }
        /// <summary></summary>



        public string Name { get; set; }
        /// <summary>FK_ForecastParameters_ForecastDeclineCurveTypes</summary> 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForecastParameterDetail> ForecastParameterDetails_ForecastDeclineCurveType { get; set; }

        /// <summary>FK_TypecurveParameters_ForecastDeclineCurveTypes</summary> 
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<TypeCurveParameter> TypeCurveParameters_ForecastDeclineCurveType { get; set; }
    }
}
